# -*- coding: utf-8 -*-
"""TCP_SERVER1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXae7TpNFTn2AM0BELQddfq3zwRr-HV_
"""

import socket

PORT = 50000
BUFSIZE = 4096
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind(("", PORT))
server.listen()

while True:
  client, add = server.accept()
  print(client, "通信要求がありました")
  data = client.recv(BUFSIZE)
  print(data.decode("UTF-8"))
  msg = input("メッセージを入力してください:")
  client.sendall(msg.encode("UTF-8"))
  client.close()