# -*- coding: utf-8 -*-
"""TCP_CLIENT1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QcSioeVES-GfxHnx4Xlun477o9E0iDAu
"""

import socket
import sys

BUFSIZE = 4096
PORT = 50000

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = input("接続先サーバーを入力してください:")

try:
  client.connect((host, PORT))
except:
  print("接続に問題があります")
  sys.exit()

msg = input("メッセージを入力してください:")
client.sendall(msg.encode("UTF-8"))
data = client.recv(BUFSIZE)
print(data.decode("UTF-8"))

client.close()